# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Maxime Sirois
description: "Hello, I'm Max and I'm passionate about finding solutions to complex problems. Data has a lot of hidden gems, and I love digging through the rubble to unearth tangible insights that had value to the business. Please visit my Github & download my resume to see what I can bring to your company. "
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Quebec, Canada"
resume_url: /docs/Maxime.Sirois.Resume.2025.2.docx
avatar_image: /img/Cropped_photo.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/maxime-sirois-b309a631b/" # Add your linkedln handle
github: "https://github.com/Max0513"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

